package ch.lkmc.goo.ui.home

import android.graphics.BitmapFactory
import android.net.Uri
import android.text.format.DateUtils
import android.text.format.Formatter
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.PickVisualMediaRequest
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.asPaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.navigationBars
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.GridItemSpan
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.PhotoCamera
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.produceState
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.CornerRadius
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.pluralStringResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.CustomAccessibilityAction
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.customActions
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.core.net.toUri
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.LifecycleResumeEffect
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import ch.lkmc.goo.BuildConfig
import ch.lkmc.goo.R
import ch.lkmc.goo.data.CameraCapture
import ch.lkmc.goo.data.ProjectStore
import ch.lkmc.goo.ui.components.ChromeButton
import ch.lkmc.goo.ui.components.ChromeIconButton
import ch.lkmc.goo.ui.components.GridBackdrop
import ch.lkmc.goo.ui.components.chromePanel
import ch.lkmc.goo.ui.theme.MeltPanel
import ch.lkmc.goo.ui.theme.NeonCyan
import ch.lkmc.goo.ui.theme.NeonMagenta
import ch.lkmc.goo.ui.theme.NeonTangerine
import ch.lkmc.goo.ui.theme.NeonViolet
import ch.lkmc.goo.ui.theme.chromeSweep
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * The In room, laid out the way the Goo room is: a chrome plate holds
 * the controls, and the work surface scrolls beneath it.
 *
 * The plate is the **console** — every way to START a goo in one place:
 * the wordmark, the GOO! dome (system Photo Picker; no permission, no
 * gallery UI of our own — Meltorama is an editor, not a browser,
 * PLAN.md §1), the snap bead, and the two bundled samples as port-hole
 * dials (procedurally generated by scripts/generate_samples.py). It
 * never scrolls away, so the door into the goo is always one tap from
 * anywhere on the shelf.
 *
 * Below it, the **shelf**: every saved goo as a grid standing on the
 * neon horizon — a browsable surface, not a three-visible-of-thirty
 * peephole. Its readout (count, cost, space left) heads the grid; the
 * destructive sweep and About sit quietly at its far end.
 */
@Composable
fun HomeScreen(
    onOpenImage: (Uri) -> Unit,
    onOpenProject: (String) -> Unit,
    viewModel: HomeViewModel = hiltViewModel(),
) {
    val pickImage = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.PickVisualMedia(),
    ) { uri -> uri?.let(onOpenImage) }

    // Snap a photo. The camera app does the capturing — Meltorama holds
    // no camera permission and asks for none (see CameraCapture).
    val context = LocalContext.current
    val hasCamera = remember(context) { CameraCapture.isAvailable(context) }
    // The URI has to survive the trip to the camera app and back, and the
    // callback is handed only a success flag. Remembered rather than
    // captured, or a process death mid-capture would return to a null.
    var pendingCapture by rememberSaveable { mutableStateOf<Uri?>(null) }
    // TakePicture is used as-is, with no subclass adding
    // FLAG_GRANT_WRITE_URI_PERMISSION. That workaround is everywhere
    // online and is obsolete here: androidx.activity 1.13.0's
    // createIntent already calls addFlags(1) and addFlags(2) — read and
    // write — which was checked against the bytecode rather than
    // assumed, because whether the camera app can write to our URI is
    // the difference between this feature working and silently
    // returning an empty file on half the devices in the world.
    val takePicture = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.TakePicture(),
    ) { saved ->
        val uri = pendingCapture
        pendingCapture = null
        // False means cancelled or failed. The scratch file is left for
        // CameraCapture's own sweep rather than deleted here: a camera
        // app that reports failure after writing something is exactly
        // the case this must not guess about.
        if (saved && uri != null) onOpenImage(uri)
    }

    val state by viewModel.uiState.collectAsStateWithLifecycle()
    // The editor writes projects behind this screen's back, so the shelf
    // is re-read on every return rather than once at composition.
    LifecycleResumeEffect(viewModel) {
        viewModel.refresh()
        onPauseOrDispose {}
    }

    var showAbout by remember { mutableStateOf(false) }
    if (showAbout) {
        AlertDialog(
            onDismissRequest = { showAbout = false },
            title = { Text(stringResource(R.string.about_title, BuildConfig.VERSION_NAME)) },
            text = { Text(stringResource(R.string.about_body)) },
            confirmButton = {
                TextButton(onClick = { showAbout = false }) {
                    Text(stringResource(R.string.about_close))
                }
            },
        )
    }

    var confirmDeleteAll by remember { mutableStateOf(false) }
    if (confirmDeleteAll) {
        AlertDialog(
            onDismissRequest = { confirmDeleteAll = false },
            title = { Text(stringResource(R.string.project_delete_all_title)) },
            text = {
                Text(
                    pluralStringResource(
                        R.plurals.project_delete_all_body,
                        state.projects.size,
                        state.projects.size,
                    ),
                )
            },
            confirmButton = {
                TextButton(
                    onClick = {
                        confirmDeleteAll = false
                        viewModel.deleteAll()
                    },
                ) { Text(stringResource(R.string.project_delete_confirm)) }
            },
            dismissButton = {
                TextButton(onClick = { confirmDeleteAll = false }) {
                    Text(stringResource(R.string.project_delete_cancel))
                }
            },
        )
    }

    var pendingDelete by remember { mutableStateOf<String?>(null) }
    pendingDelete?.let { id ->
        AlertDialog(
            onDismissRequest = { pendingDelete = null },
            title = { Text(stringResource(R.string.project_delete_title)) },
            text = { Text(stringResource(R.string.project_delete_body)) },
            confirmButton = {
                TextButton(
                    onClick = {
                        pendingDelete = null
                        viewModel.delete(id)
                    },
                ) { Text(stringResource(R.string.project_delete_confirm)) }
            },
            dismissButton = {
                TextButton(onClick = { pendingDelete = null }) {
                    Text(stringResource(R.string.project_delete_cancel))
                }
            },
        )
    }

    Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.background) {
        Box(modifier = Modifier.fillMaxSize()) {
            GridBackdrop()
            Column(modifier = Modifier.fillMaxSize()) {
                Console(
                    // The empty room is a poster and gets the full pitch;
                    // a room with work in it is a workbench, and the
                    // pitch would only push the shelf down.
                    showPitch = state.projects.isEmpty(),
                    hasCamera = hasCamera,
                    onGoo = {
                        pickImage.launch(
                            PickVisualMediaRequest(
                                ActivityResultContracts.PickVisualMedia.ImageOnly,
                            ),
                        )
                    },
                    onSnap = {
                        val file = CameraCapture.nextFile(context)
                        val uri = CameraCapture.uriFor(context, file)
                        pendingCapture = uri
                        takePicture.launch(uri)
                    },
                    onOpenImage = onOpenImage,
                )
                Box(modifier = Modifier.weight(1f)) {
                    if (state.projects.isEmpty()) {
                        Column(
                            modifier = Modifier
                                .align(Alignment.Center)
                                .padding(horizontal = 40.dp),
                            horizontalAlignment = Alignment.CenterHorizontally,
                        ) {
                            Text(
                                text = stringResource(R.string.home_shelf_empty),
                                style = MaterialTheme.typography.bodyMedium,
                                color = MaterialTheme.colorScheme.onSurfaceVariant,
                                textAlign = TextAlign.Center,
                            )
                            AboutButton { showAbout = true }
                        }
                    } else {
                        ShelfGrid(
                            projects = state.projects,
                            usedBytes = state.usedBytes,
                            freeBytes = state.freeBytes,
                            onOpenProject = onOpenProject,
                            onDelete = { pendingDelete = it },
                            onDeleteAll = { confirmDeleteAll = true },
                            onAbout = { showAbout = true },
                        )
                    }
                }
            }
        }
    }
}

/**
 * The console plate: identity on top, then one row of instruments —
 * snap bead · GOO! dome · two sample port-holes — with the dome dead
 * center whatever flanks it (the side slots share the leftover width).
 */
@Composable
private fun Console(
    showPitch: Boolean,
    hasCamera: Boolean,
    onGoo: () -> Unit,
    onSnap: () -> Unit,
    onOpenImage: (Uri) -> Unit,
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .chromePanel(RoundedCornerShape(bottomStart = 18.dp, bottomEnd = 18.dp))
            .statusBarsPadding()
            .padding(top = 10.dp, bottom = 14.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        // Only the type gets side padding: the instrument row below
        // measures its gaps from the plate's true edges.
        Column(
            modifier = Modifier.padding(horizontal = 20.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
        ) {
            // The real logo, not the code-drawn stand-in it replaced:
            // a transparent WebP in drawable-nodpi (density-independent;
            // the layout decides how big it draws), cut and scaled from
            // media-sources/logo.png. One label to TalkBack, the way the
            // wordmark before it read.
            Image(
                painter = painterResource(R.drawable.logo_wordmark),
                contentDescription = stringResource(R.string.app_name_full) +
                    " " + stringResource(R.string.app_model),
                contentScale = ContentScale.FillWidth,
                modifier = Modifier.fillMaxWidth(0.8f),
            )
            Spacer(modifier = Modifier.height(8.dp))
            Text(
                text = stringResource(R.string.home_tagline),
                style = MaterialTheme.typography.titleSmall,
                color = NeonCyan,
                textAlign = TextAlign.Center,
            )
            if (showPitch) {
                Spacer(modifier = Modifier.height(4.dp))
                Text(
                    text = stringResource(R.string.home_subtagline),
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    textAlign = TextAlign.Center,
                )
            }
        }
        Spacer(modifier = Modifier.height(12.dp))
        // One even rhythm across the whole plate: edge · snap · dome ·
        // sample · sample · edge, every gap the same. SpaceEvenly also
        // absorbs narrow screens by shrinking the gaps, not the dials —
        // the instruments sum to 252dp, inside even a 320dp plate.
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceEvenly,
            verticalAlignment = Alignment.CenterVertically,
        ) {
            if (hasCamera) {
                ChromeIconButton(
                    icon = Icons.Filled.PhotoCamera,
                    contentDescription = stringResource(R.string.home_take_photo),
                    color = NeonCyan,
                    selected = false,
                    onClick = onSnap,
                )
            }
            ChromeButton(
                label = stringResource(R.string.home_enter_goo),
                color = NeonMagenta,
                onClick = onGoo,
                size = 112.dp,
                breathe = true,
            )
            SampleThumb(
                assetPath = "samples/goo-guy.png",
                labelRes = R.string.sample_goo_guy,
                glow = NeonMagenta,
                size = 46.dp,
                onOpenImage = onOpenImage,
            )
            SampleThumb(
                assetPath = "samples/candy-blobs.png",
                labelRes = R.string.sample_candy_blobs,
                glow = NeonCyan,
                size = 46.dp,
                onOpenImage = onOpenImage,
            )
        }
    }
}

/** The shelf: every saved goo, newest first, standing on the horizon. */
@Composable
private fun ShelfGrid(
    projects: List<ProjectStore.Summary>,
    usedBytes: Long,
    freeBytes: Long,
    onOpenProject: (String) -> Unit,
    onDelete: (String) -> Unit,
    onDeleteAll: () -> Unit,
    onAbout: () -> Unit,
) {
    // Tiles scroll under the transparent nav bar and the last row clears
    // it — inset as content padding, not as a wall.
    val navBottom = WindowInsets.navigationBars.asPaddingValues().calculateBottomPadding()
    LazyVerticalGrid(
        columns = GridCells.Adaptive(minSize = 100.dp),
        modifier = Modifier.fillMaxSize(),
        contentPadding = PaddingValues(
            start = 20.dp,
            end = 20.dp,
            top = 10.dp,
            bottom = navBottom + 8.dp,
        ),
        horizontalArrangement = Arrangement.spacedBy(12.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        item(span = { GridItemSpan(maxLineSpan) }) {
            // The instrument readout: what the shelf holds, what it
            // costs, and what is left. Nothing evicts on its own, so
            // this is the number the decision is made on — and
            // labelSmall is the console's monospace readout face,
            // which is exactly what these are.
            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                Text(
                    text = pluralStringResource(
                        R.plurals.home_projects_usage,
                        projects.size,
                        projects.size,
                        formatBytes(usedBytes),
                        formatBytes(freeBytes),
                    ),
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    textAlign = TextAlign.Center,
                )
                // The one gesture the tiles don't show, in the readout's
                // own quiet voice.
                Text(
                    text = stringResource(R.string.home_projects_hint),
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    textAlign = TextAlign.Center,
                )
            }
        }
        // Keyed by id: deleting a tile from the middle must not hand its
        // decoded preview to the project that slides into its slot.
        items(projects, key = { it.id }) { project ->
            ProjectTile(
                project = project,
                onOpen = { onOpenProject(project.id) },
                onDelete = { onDelete(project.id) },
            )
        }
        item(span = { GridItemSpan(maxLineSpan) }) {
            // The sweep and the fine print, past everything they refer
            // to — the bottom of the shelf, not the middle of the room.
            Row(
                modifier = Modifier.fillMaxWidth(),
                // Daylight between the sweep and About: one throws the
                // whole shelf away, the other is fine print.
                horizontalArrangement = Arrangement.spacedBy(12.dp, Alignment.CenterHorizontally),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                TextButton(onClick = onDeleteAll) {
                    Text(
                        text = stringResource(R.string.project_delete_all),
                        style = MaterialTheme.typography.labelMedium,
                        color = NeonTangerine,
                    )
                }
                AboutButton(onClick = onAbout)
            }
        }
    }
}

@Composable
private fun AboutButton(onClick: () -> Unit) {
    TextButton(onClick = onClick) {
        Text(
            text = stringResource(R.string.home_about),
            style = MaterialTheme.typography.labelMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
    }
}

/**
 * One saved project as a screen in a chrome bezel — a rectangle, not the
 * samples' port-hole, because this is a document you were working on
 * rather than a picture on the shelf. Sized by its grid cell; the 96:84
 * screen proportion rides along.
 *
 * Tap resumes it; a long press (or the TalkBack action) offers to throw
 * it away. The preview is the goo as it was saved, not the source photo:
 * ProjectStore renders it through the same replay the export uses.
 */
@Composable
private fun ProjectTile(
    project: ProjectStore.Summary,
    onOpen: () -> Unit,
    onDelete: () -> Unit,
) {
    // Keyed on the save time as well as the path: a re-saved project keeps
    // the same preview file, and only the timestamp says it holds a
    // different picture now.
    val thumb by produceState<ImageBitmap?>(
        initialValue = null,
        project.thumbnail,
        project.updatedAtMillis,
    ) {
        val file = project.thumbnail
        value = if (file == null) null else withContext(Dispatchers.IO) {
            // A save that could not render a preview (no GL surface) still
            // produced a project: the tile shows the empty screen instead.
            runCatching { BitmapFactory.decodeFile(file.path)?.asImageBitmap() }.getOrNull()
        }
    }
    val context = LocalContext.current
    val label = stringResource(R.string.project_open)
    val deleteLabel = stringResource(R.string.project_delete_confirm)
    val age = remember(project.updatedAtMillis, context) {
        // The span alone ("Yesterday", "26 min. ago"), not date-and-time:
        // a tile caption is narrow, and the longer form ellipsized every
        // tile on the shelf to an identical "Yesterday, …". Still the
        // Context-taking variant: it formats in the CONTEXT's locale, so
        // a per-app language override (locales_config) reaches this
        // label too — the static overloads read the system locale.
        DateUtils.getRelativeTimeSpanString(context, project.updatedAtMillis).toString()
    }
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .aspectRatio(96f / 84f)
                .semantics {
                    contentDescription = "$label, $age"
                    // Long-press is invisible to TalkBack; the same verb
                    // has to exist as an action.
                    customActions = listOf(CustomAccessibilityAction(deleteLabel) { onDelete(); true })
                }
                .combinedClickable(role = Role.Button, onLongClick = onDelete, onClick = onOpen),
            contentAlignment = Alignment.Center,
        ) {
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .clip(TILE_SHAPE)
                    .background(MeltPanel),
            ) {
                thumb?.let { image ->
                    Image(
                        bitmap = image,
                        contentDescription = null,
                        contentScale = ContentScale.Crop,
                        modifier = Modifier.fillMaxSize(),
                    )
                }
            }
            // The bezel, drawn over the glass so the screen sits inside it.
            Canvas(modifier = Modifier.fillMaxSize()) {
                val rim = 3.dp.toPx()
                drawRoundRect(
                    brush = chromeSweep(),
                    topLeft = Offset(rim / 2f, rim / 2f),
                    size = Size(size.width - rim, size.height - rim),
                    cornerRadius = CornerRadius(TILE_CORNER.toPx()),
                    style = Stroke(width = rim),
                )
                // A violet pilot light along the bottom lip: this screen is
                // powered up, unlike the samples' cold port-holes.
                drawRoundRect(
                    brush = Brush.verticalGradient(
                        colors = listOf(Color.Transparent, NeonViolet.copy(alpha = 0.35f)),
                    ),
                    topLeft = Offset(rim, size.height * 0.6f),
                    size = Size(size.width - rim * 2f, size.height * 0.4f - rim),
                    cornerRadius = CornerRadius(TILE_CORNER.toPx()),
                )
            }
        }
        Spacer(modifier = Modifier.height(4.dp))
        Text(
            text = age,
            modifier = Modifier.fillMaxWidth(),
            style = MaterialTheme.typography.labelSmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            textAlign = TextAlign.Center,
            maxLines = 1,
            overflow = TextOverflow.Ellipsis,
        )
    }
}

private val TILE_CORNER = 12.dp
private val TILE_SHAPE = RoundedCornerShape(12.dp)

/**
 * Bytes as the platform would say them ("148 MB"), in the app's locale —
 * [Formatter] takes a Context precisely so the units and the decimal
 * separator follow it, which a hand-rolled divide-by-1024 would not.
 */
@Composable
private fun formatBytes(bytes: Long): String {
    val context = LocalContext.current
    return remember(bytes, context) { Formatter.formatFileSize(context, bytes) }
}

/**
 * One bundled sample as a tappable port-hole: the image behind a milled
 * chrome ring, lit by its own neon. Decoded off the main thread at
 * quarter resolution — the full image only loads if picked (the editor
 * re-reads the asset through the session-file pipeline).
 */
@Composable
private fun SampleThumb(
    assetPath: String,
    labelRes: Int,
    glow: Color,
    size: Dp,
    onOpenImage: (Uri) -> Unit,
) {
    val context = LocalContext.current
    val thumb by produceState<ImageBitmap?>(initialValue = null, assetPath) {
        value = withContext(Dispatchers.IO) {
            // A missing/unreadable asset degrades to the placeholder disc,
            // never a crash (the paths are hardcoded next to the assets,
            // but a rename shouldn't take the In room down).
            try {
                context.assets.open(assetPath).use { stream ->
                    BitmapFactory.decodeStream(
                        stream,
                        null,
                        BitmapFactory.Options().apply { inSampleSize = 4 },
                    )
                }?.asImageBitmap()
            } catch (e: java.io.IOException) {
                null
            }
        }
    }
    val label = stringResource(labelRes)
    Box(
        modifier = Modifier
            .size(size)
            .semantics { contentDescription = label }
            .clickable(role = Role.Button) {
                onOpenImage("file:///android_asset/$assetPath".toUri())
            },
        contentAlignment = Alignment.Center,
    ) {
        Canvas(modifier = Modifier.fillMaxSize()) {
            val outer = this.size.minDimension / 2f
            val c = Offset(this.size.width / 2f, this.size.height / 2f)
            drawCircle(
                brush = Brush.radialGradient(
                    colors = listOf(glow.copy(alpha = 0.35f), Color.Transparent),
                    center = c,
                    radius = outer,
                ),
                radius = outer,
                center = c,
            )
            val ringWidth = outer * 0.14f
            drawCircle(
                brush = chromeSweep(),
                radius = outer * 0.90f - ringWidth / 2f,
                center = c,
                style = Stroke(width = ringWidth),
            )
        }
        // The glass itself, inside the ring. An undecoded sample shows the
        // empty port-hole in panel gunmetal rather than a hole in the UI.
        Box(
            modifier = Modifier
                .size(size * 0.76f)
                .clip(CircleShape)
                .background(MeltPanel),
        ) {
            thumb?.let { image ->
                Image(
                    bitmap = image,
                    contentDescription = null,
                    contentScale = ContentScale.Crop,
                    modifier = Modifier
                        .fillMaxSize()
                        .clip(CircleShape),
                )
            }
        }
    }
}
